### ISSUE TITLE
Method must have a return type

### ISSUE THREAD

**Issue by NathanVG** [DavidVollmers/Ignis#47]
Hi, 

I'm trying to make a simple toggle to show or hide a sub menu, however when trying to do it like in the Ignis [docs ](https://ignis.dvolper.dev/docs/components/reactivity)I get this error:

![image](https://github.com/DavidVollmers/Ignis/assets/3620183/53ac1035-0d5c-41a4-a75d-5399faf7652d)

I don't really get what I'm doing wrong, when I add void I get a different errors: 

![image](https://github.com/DavidVollmers/Ignis/assets/3620183/c44283c8-1cb3-4776-99f5-b3bd01f9477c)

I'm using .net8

**Comment by DavidVollmers** [comment]
The `ReactiveValue` should be initialized in the constructor of your component. In the docs this component is named `ReactiveCounter`. In your case it is named how you named the file of your component.

A constructor in C# has no return type. But since the name (`ReactiveShowSubMenu`) is not the name of your component, the compiler thinks you are trying to define a method, which always requires a return type.

I will add a comment to the example to make clear to initialize the reactive value in the constructor of the component!

**Comment by NathanVG** [comment]
Thank you for clarifying, like you said it wasn't immediately clear from the docs that it was a constructor for the page, which is a bit confusing if you're not used to OOP. I think clarifying this in the docs is a great idea.
