### ISSUE TITLE
ListBox (Select) doesn't scroll when using keyboard arrows

### ISSUE THREAD

**Issue by panoukos41** [DavidVollmers/Ignis#52]
Hey, as I was trying the ListBox with a lot of items I noticed that the keyboard doesn't scroll the list. The items get's selected etc but you can't actually see it.

Actual behavior
![msedge_6](https://github.com/DavidVollmers/Ignis/assets/20771798/a6035136-f2bf-43f8-8e38-8af127645689)

Expected behavior (from official library)
![msedge_4](https://github.com/DavidVollmers/Ignis/assets/20771798/3ca95751-ff0b-4861-b84a-532d230147b3)

**Comment by panoukos41** [comment]
Hey @DavidVollmers are you working on this or could I give it a try? I implemented a search just like html `select` element using the `onkeydown` on a `ListBox`. It scrolls the itme found in place so I would love to give it a try and then maybe try to PR my implementation for the search using keydown as a feature 😃

**Comment by DavidVollmers** [comment]
Hey there! 

Feel free to give it a try, although the scroll implementation will be a little bit tricky here.

The keydown logic is implemented here: https://github.com/DavidVollmers/Ignis/blob/8605ab346f475708461dcf33a2c2ceb9722d3d6c/packages/Tailwind/Ignis.Components.HeadlessUI/Aria/AriaPopupExtensions.cs#L21

But I think the best way to solve this issue is to overwrite the `OnAfterOpen` logic in all popups to scroll to its active descendant. 
For the listbox this could happen here:
https://github.com/DavidVollmers/Ignis/blob/8605ab346f475708461dcf33a2c2ceb9722d3d6c/packages/Tailwind/Ignis.Components.HeadlessUI/Listbox.cs#L270

**Comment by panoukos41** [comment]
I see, I will give it a try with that in mind!

**Comment by DavidVollmers** [comment]
This is fixed with release [1.4.0](https://github.com/DavidVollmers/Ignis/releases/tag/1.4.0)
